export const Constants = {
  MyProfile: "My Profile",
  GroupChat: "Group Chat",
  Logout: "Logout",
  ProfileInfo: "Personal Info",
  ProfileInfoSubText: "Basic info, like your name and photo",
  ProfileHeaderTitle: "Profile",
  ProfileHeaderSubText: "Some info may be visible",
  Edit: "Edit",
  Photo: "Photo",
  Name: "Name",
  Bio: "Bio",
  Phone: "Phone",
  Email: "Email",
  Password: "Password",
  Asterisks: "***************",
} as const;
