export const Constants = {
  MyProfile: "My Profile",
  GroupChat: "Group Chat",
  Logout: "Logout",
  ProfileInfo: "Personal Info",
  ProfileInfoSubText: "Basic info, like your name and photo",
  ProfileHeaderTitle: "Profile",
  ProfileHeaderSubText: "Some info may be visible",
  Edit: "Edit",
  Photo: "Photo",
  Name: "Name",
  NamePlaceholder: "Enter your name...",
  Bio: "Bio",
  BioPlaceholder: "Enter your biography...",
  Phone: "Phone",
  PhonePlaceholder: "Enter your phone number...",
  Email: "Email",
  EmailPlaceholder: "Enter your email...",
  Password: "Password",
  CurrentPassword: "Current Password",
  CurrentPasswordPlaceholder: "Enter your current password...",
  NewPassword: "New Password",
  NewPasswordPlaceholder: "Enter your new password...",
  Asterisks: "***************",
  Back: "Back",
  ChangeInfo: "Change Info",
  ChangeInfoSub: "Changes will be reflected to every service",
  AddPhoto: "Add Photo",
  Save: "Save",
} as const;
