export const Constants = {
  CreatedBy: 'created by',
  DeveloperName: 'TorenIvan',
  ChallengeSite: 'devChallenges.io',
  DeveloperGitHubProfile: 'https://github.com/TorenIvan',
  LightPalette: 'light-theme',
  DarkPalette: 'dark-theme',
  Theme: 'theme',
  Credentials: 'credentials',
  MyProfile: 'My Profile',
  GroupChat: 'Group Chat',
  Logout: 'Logout',
  ProfileInfo: 'Personal Info',
  ProfileInfoSubText: 'Basic info, like your name and photo',
  ProfileHeaderTitle: 'Profile',
  ProfileHeaderSubText: 'Some info may be visible',
  ProfileUpdatedSuccess: 'Profile updated successfully',
  Edit: 'Edit',
  Photo: 'Photo',
  Name: 'Name',
  NamePlaceholder: 'Enter your name...',
  Bio: 'Bio',
  BioPlaceholder: 'Enter your biography...',
  Phone: 'Phone',
  PhonePlaceholder: 'Enter your phone number...',
  Email: 'Email',
  EmailPlaceholder: 'Enter your email address...',
  Password: 'Password',
  CurrentPassword: 'Current Password',
  CurrentPasswordPlaceholder: 'Enter your current password...',
  NewPassword: 'New Password',
  NewPasswordPlaceholder: 'Enter your new password...',
  Asterisks: '***************',
  Back: 'Back',
  ChangeInfo: 'Change Info',
  ChangeInfoSub: 'Changes will be reflected to every service',
  AddPhoto: 'Add Photo',
  ChangePhoto: 'Change Photo',
  Save: 'Save',
  Saving: 'Saving...',
  NotAdded: 'Not added...',
  FormHeader:
    'Master web development by making real-life projects. There are multiple paths for you to choose.',
  AlreadyAMember: 'Already a member?',
  AroundTheWorld: 'around the world',
  JoinLearners: 'Join thousands of learners from',
  SocialProfilesFormText: 'or continue with these social profiles',
  SignInButtonTextLoad: 'Signing...',
  SignInButtonText: 'Sign In!',
  RegisterButtonText: 'Register Now!',
  Registering: 'Registering...',
  Register: 'Register',
  Login: 'Login',
  SignIn: 'Sign In',
  DontHaveAnAccount: "Don't have an account yet?",
  ForgotPassword: 'Forgot Password',
  ForgotPasswordLink: 'Forgot your password?',
  ForgotPasswordParagraph:
    'Please provide your email address that you used when you signed up for your account',
  Continue: 'Continue',
  Continuing: 'Continuing...',
  ResetPassword: 'Reset Password',
  ResetPasswordParagraph:
    'Enter your new password and confirm it in order to proceed with resetting it',
  Resetting: 'Resetting...',
  ConfirmHeader: 'Congratulations!',
  ConfirmHeaderLoading: 'Confirmation in progress',
  ConfirmHeaderError: "Sorry! We couldn't confirm your email address.",
  ConfirmParagraph: 'Your email has been confirmed. You can now sign in to the application.',
  ConfirmParagraphLoading: 'This might take a few seconds...',
  ConfirmParagraphError: 'Sign In to send you a new confirmation link',
  BackToSignIn: 'Back to Sign In',
  ConfirmEmailMessage:
    'Almost done! An email will be sent to your account soon. Follow the instructions to verify your account.',
  ResetPasswordEmailMessage:
    'Almost done! An email will be sent to your account soon. Follow the instructions to reset your password.',
  PasswordResetMessage:
    'Congratulations! Your password has been reset. You can now sign in with your new password.',
  LoginHeaderError: "Sorry! We couldn't confirm your identity.",
  LoginHeaderLoading: 'Authorize operation in progress might take a few seconds...',
  LoginParagraphError: 'Something went wrong with social login. Please, try again!',
} as const;
