const encodedDBPassword = encodeURI(String(process.env.DB_PASSWORD));
const DatabaseUri = `mongodb://${process.env.DB_USERNAME}:${encodedDBPassword}@${process.env.DB_URI}&AuthSource=${process.env.DB_NAME}`;

export const EnvironmentVariables = {
  DatabaseUri: DatabaseUri,
  ServerUri: process.env.SERVER_URI!,
  DatabaseName: process.env.DB_NAME,
  IsProduction: process.env.NODE_END === 'production',
  Access_Token_Secret: process.env.ACCESS_TOKEN_SECRET!,
  Refresh_Token_Secret: process.env.REFRESH_TOKEN_SECRET!,
  Access_Token_Expiration_Time: process.env.ACCESS_TOKEN_SECRET_EXPIRATION!,
  Refresh_Token_Expiration_Time: process.env.REFRESH_TOKEN_SECRET_EXPIRATION!,
  Cookie_Name: process.env.COOKIE_NAME!,
  Reset_Pass_Cookie_Name: process.env.RESET_PASS_COOKIE_NAME!,
  Reset_Pass_Cookie_Secret: process.env.RESET_PASS_SECRET!,
  Reset_Pass_Cookie_Expiration_Time: process.env.RESET_PASS_COOKIE_EXPIRATION_TIME!,
  Cookie_Secret: process.env.COOKIE_SECRET!,
  Salt_Size: process.env.SALT_SIZE!,
  Email_Secret: process.env.EMAIL_SECRET!,
  Email_Token_Expiration_Time: process.env.EMAIL_TOKEN_EXPIRATION!,
  Email_Api_Key: process.env.RESEND_API_KEY!,
  Email_Username: process.env.EMAIL_USERNAME!,
  Email_Verification_Uri: process.env.EMAIL_URI_VERIFICATION!,
  Reset_Pass_Uri: process.env.RESET_PASS_URI!,
  Facebook_App_Id: process.env.FACEBOOK_APP_ID!,
  Facebook_App_Secret: process.env.FACEBOOK_APP_SECRET!,
  Facebook_App_Redirect_Uri: process.env.FACEBOOK_APP_REDIRECT_URI!,
  Cookie_Name_Social_Profile: process.env.COOKIE_NAME_SOCIAL_PROFILE!,
  Log_Level: process.env.LOG_LEVEL!,
} as const;
